# Placeholders to be rewritten by launch file:
# - <entity> : Should be replaced by entity name: For example "andino", "andino_1", "andino_2".

- ros_topic_name: "odom"
  gz_topic_name: "/model/<entity>/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# odom <-> base_link transform
- ros_topic_name: "tf"
  gz_topic_name: "/model/<entity>/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "joint_states"
  gz_topic_name: "/world/gazebo_world/model/<entity>/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "camera_info"
  gz_topic_name: "/world/gazebo_world/model/<entity>/link/base_link/sensor/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "image_raw"
  gz_topic_name: "/world/gazebo_world/model/<entity>/link/base_link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# ===== Lidar front currently spawned under base_link (gpu_lidar/ray) =====
- ros_topic_name: "scan"
  gz_topic_name: "/world/gazebo_world/model/<entity>/link/base_link/sensor/sensor_ray_front/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "scan/points"
  gz_topic_name: "/world/gazebo_world/model/<entity>/link/base_link/sensor/sensor_ray_front/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "cmd_vel"
  gz_topic_name: "/model/<entity>/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/imu/data"
  gz_topic_name: "/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# ===== Ultrasonic (LaserScan أحادي/ضيق) إلى ROS =====
# استخدم هذا الماب لو عايز ROS topic ثابت باسم /ultrasonic/scan (من نفس الحساس الحالي):
- ros_topic_name: "/ultrasonic/scan"
  gz_topic_name: "/world/gazebo_world/model/<entity>/link/base_link/sensor/sensor_ray_front/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# ===== بديل لاحقًا: لو نقلت الحساس إلى ultrasonic_link باسم ultrasonic_front، فعّل البلوك ده بدلًا من الأعلى =====
# - ros_topic_name: "/ultrasonic/scan"
#   gz_topic_name: "/world/gazebo_world/model/<entity>/link/ultrasonic_link/sensor/ultrasonic_front/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS
